### ISSUE TITLE
mettre le pdf du shéma des tables sur Github

### ISSUE THREAD

**Issue by nanls** [Athenais/M2BI-db-project#14]

**Comment by NicolasBourassin** [comment]
Fait ; c'est un .png, mais je suppose que ça pose pas de soucis et c'est plus simple à insérer au sein d'un rapport.

**Comment by nanls** [comment]
je vous propose ce nouveau schéma (il me parait résoudre les 'problèmes' que j'ai mentionné dans les divers commentaires du précédent schéma). : 

![capture du 2017-03-16 22-17-49](https://cloud.githubusercontent.com/assets/3973705/24018979/749aaa3a-0a96-11e7-90e9-a92de9aa7a98.png)

**Comment by nanls** [comment]
done
