### ISSUE TITLE
Etape 3 : Intégration dans la base de données

### ISSUE THREAD

**Issue by nanls** [Athenais/M2BI-db-project#3]
> Vous devrez à partir des programmes utilisés formater les données pour pouvoir les insérer dans la base de données (commande INSERT INTO...).

**Comment by jecarvaill** [comment]
Dans la table angle, il serait judicieux de remplacer atom_idx par res_idx car l'angle phi et psi ne sont pas calculés sur les mêmes atomes.

Ex:
- Phi : angle entre N et Ca
- Psi : angle entre Ca et C
