### ISSUE TITLE
"un graphe de Ramachandran pour chaque méthode réalisé devra être affiché" pourquoi nous on en a qu'un ? 

### ISSUE THREAD

**Issue by nanls** [Athenais/M2BI-db-project#59]

**Comment by NicolasBourassin** [comment]
Le graphe de ramachandran est généré avec les angles phi et psi, vu que les 2 méthodes s'appuient sur les mêmes angles ça reviendrait juste à dupliquer le même graphe ... à mon avis c'est une mauvaise formulation pour dire "quelque soit la méthode utilisée"

**Comment by nanls** [comment]
Ben je sais pas, look le petit schéma d'explication. :/

Le 16 avril 2017 à 17:25, NicolasBourassin <notifications@github.com> a
écrit :

**Comment by nanls** [comment]
C'est bon, j'ai compris, cf #61
