### ISSUE TITLE
(Bonus) Etape 6 : Conception et intégration de sorties complexes

### ISSUE THREAD

**Issue by nanls** [Athenais/M2BI-db-project#6]
> Vous devrez permettre à l’utilisateur d’afficher les cartes de Ramachandran d’un fichier PDB particulier, et ce à partir des coordonnées Phi et Psi contenues dans le fichier PDB (à vous d’inclure ces informations dans la base de données). Pour ce faire, vous pourrez utiliser l’outil MatPlotLib en R

**Comment by nanls** [comment]
oh, du coup, c'est optionnel... great.

**Comment by jecarvaill** [comment]
Ca normalement, c'est fini \o/
