### ISSUE TITLE
ca buggue quand le pdb est deja dans la base, non ? (A verifier)

### ISSUE THREAD

**Issue by nanls** [Athenais/M2BI-db-project#70]

**Comment by jecarvaill** [comment]
Pas de bug, chez moi. Marque success à l'upload mais ne traite pas ne nouveau fichier.

**Comment by nanls** [comment]
j'ai trouvé d'ou venait le pb que j'avais : les pdbs s'appellent pdb1234.pdb

Ce pb là est resolution, je passe au suivant. XD 

Teste dans tout les sens et fait des issues.

**Comment by jecarvaill** [comment]
Mais j’ai toujours pas les cartes qui s’affichent chez moi pour results T.T
