### ISSUE TITLE
la génération des annotations ne marchent pas

### ISSUE THREAD

**Issue by nanls** [Athenais/M2BI-db-project#72]
sh: 1: cannot create temp/1a0j.dssp: Directory nonexistent
FileNotFoundError: [Errno 2] No such file or directory: 'temp/1a0j.dssp'

**Comment by nanls** [comment]
putain, ya pas de dossier temp...

**Comment by nanls** [comment]
mais tu ne l'avais pas deja fait, ça , @jecarvaill ? :/

**Comment by jecarvaill** [comment]
Sii T.T

**Comment by jecarvaill** [comment]
c'est dans ma fonction compute_ramachandran_map

**Comment by nanls** [comment]
mais oui, mais cha aussi elle save ses truc dans temp. Et compute ramap c'est apres.

**Comment by jecarvaill** [comment]
bon bah on le met dans views.py ou app.py ?

**Comment by nanls** [comment]
je l'ai mis dans le sh

**Comment by jecarvaill** [comment]
OK
