### ISSUE TITLE
Problème map

### ISSUE THREAD

**Issue by jecarvaill** [Athenais/M2BI-db-project#78]
Lorsqu'il y a plus d'une chaine dans le fichier pdb, il manque une partie des angles considérées.
Il y a le bon nombre d'annotations mais le nombre d'angle n'est pas le bon selon moi.

**Comment by jecarvaill** [comment]
Du coup la génération de la carte ne semble fonctionnait que si il y a une chaine mais le problème semble être avant /!\

/!\ pas le même nombre d'annotations et d'angles

**Comment by nanls** [comment]
wow. J'ai rien compris. XD

**Comment by nanls** [comment]
je viens de lancer le code de novo. J'ai genre aucune erreur d'execution. Je sens que ca va etre dur à débugger. XD

**Comment by jecarvaill** [comment]
En gros j'ai constaté que lorsque je veux créer une map et que je transforme les annotations (string) en une liste de caractère, la taille de cette liste était beaucoup plus grande que la taille de la liste des angles phi psi.

Ce que je pense, c'est que l'on toque uniquement les angles de la chaine A.
Car lorsqu'un pdb est constitué d'une seule chaine, ça fonctionne. Sinon ça ne fonctionne pas.

par exemple pour le pdb 1pmb.pdb il y a 300 annotations pour 150 angles.

**Comment by nanls** [comment]
okay. C'est cheloux.

**Comment by jecarvaill** [comment]
Le pire c'est que j'ai testé sur plein de pdb 5b6j, 5j4k, 6tim ...

**Comment by nanls** [comment]
bon, si le pb c'est lié à ça, c'est normal que ça buggue sur plein. ^^

**Comment by nanls** [comment]
ha, c'est bon. je vois o`u c'est.

**Comment by nanls** [comment]
oh, alors là, il faut q'on se mette d'accord. XD 

on a un pdb. Le pdb a une séquence, des chaines et des angles. 
la séquences, c'est toutes les chaines concaténées. Du coup, on fait quoi  : 
on numérote le début et la fin des chaines par rapport à la séquence (c'est pas ce qui est fait actuellement) et idem pour les angles ?

**Comment by nanls** [comment]
je tente un truc, on verra si ça résout le pb.

**Comment by nanls** [comment]
arg, c'est là ou si on avait fait plus de tests sur les résidus manquants, ca aurait été cool... :/

**Comment by nanls** [comment]
perso, meme avec une chaine ca s'affiche pas non plus. mais au moins l'iamge est là. XD

**Comment by nanls** [comment]
je suis en train de bidouiller un truc qui a semble t-il aucun rapport (les index des atoms), et je tombe sur cette erreur : 

>    phi = np.rad2deg(phi)
    AttributeError: 'float' object has no attribute 'rad2deg'


une idée, @jecarvaill ?

**Comment by jecarvaill** [comment]
Hum c'est bizarre ça convertit juste une liste en une autre liste tu es sûr que phi et psi sont toujours des listes de float avec ta modification ?

**Comment by jecarvaill** [comment]
Tu as printé phi ou psi pour voir quelle tête ça a ?

**Comment by nanls** [comment]
tain, on obtient effectivement moins d'angles que d'aa dans la séquences.

**Comment by jecarvaill** [comment]
Est ce qu'une boucle sur toutes les chaines serait la solution, lorsque tu récupères les angles ?

**Comment by jecarvaill** [comment]
Avec biopython je veux dire. Lors du remplissage de la bdd.

**Comment by nanls** [comment]
en fait, je me demande si c'est pas plutot l'indiciation du start stop de la chaine qui est faux. Je teste un autre truc.

**Comment by jecarvaill** [comment]
Si t'arrive à récupérer quelles sont les chaines de la prot. Puis ensuite bouclé sur les chaines pour récupérer dans le fichier model.py avec la commande: 
angles = pp.get_phi_psi_list()
ligne 125

**Comment by jecarvaill** [comment]
Oui à moins que ce soit l'indication.

**Comment by nanls** [comment]
non, mais justement, c'est deja ce que j'ai là. 
en gros, je viens de tester avec le pdb 1a92:

pour les infos du pdb : 
![image](https://cloud.githubusercontent.com/assets/3973705/25091108/99e0103c-2387-11e7-9030-dbc1dd9efaee.png)

les séquences concaténées c'est ça : 
`GREDILEQWVSGRKKLEELERDLRKLKKKIKKLEEDNPWLGNIKGIIGKYGREDILEQWVSGRKKLEELERDLRKLKKKIKKLEEDNPWLGNIKGIIGKYGREDILEQWVSGRKKLEELERDLRKLKKKIKKLEEDNPWLGNIKGIIGKYGREDILEQWVSGRKKLEELERDLRKLKKKIKKLEEDNPWLGNIKGIIGK`

sa longuerur c'est 199.
et j'ai bien 199 angles dans la bd. 

or pour les chaines j'ai ca : 
![image](https://cloud.githubusercontent.com/assets/3973705/25091086/780eb076-2387-11e7-9a68-4e567bf84adc.png)

**Comment by nanls** [comment]
mais en fait, tu t'en fout des chaines toi, non ?
Ca devrait marcher, comme ça, les ramap, nop ?

**Comment by jecarvaill** [comment]
Bon oui mais c'est les annotations qui posent problème. Pourquoi sont elles plus grandes en terme de taille que le nombre d'angles ?

**Comment by nanls** [comment]
ha, oui, c'est vrai. Ca j'ai pas encore regardé. XD

**Comment by jecarvaill** [comment]
Je voudrais éviter de faire un truc pas très propre qui fait une sous chaine d'annotation. Je pense pas que ce soit la solution de faire annotation[1:len(phi)]

**Comment by nanls** [comment]
ha, non, mais ca en fait, c'est bon. 
je résolue ce pd, c'est que les angles étaient pas bien numéroté. je te poste ça.

**Comment by jecarvaill** [comment]
ok super

**Comment by nanls** [comment]
@jecarvaill : t'as mergé, mais ca marche vraiment chez toi ? 
si oui, tu peux faire les captures d'écran pour le rapport, stp ?

**Comment by jecarvaill** [comment]
Je corrige là enfin j'essaie.

**Comment by jecarvaill** [comment]
Le code n'est pas encore tout à fait au point

**Comment by nanls** [comment]
ha, okay. Mais du coup, coté bdd, c'est bon ?

**Comment by nanls** [comment]
tu pouras m'expliquéer le pb, quand t'auras fini, parce que j'ai pas pigé. XD 

je fais faire les contraintes d'intégrité de la bdd, là.

**Comment by jecarvaill** [comment]
Alors de ce que j'ai compris, c'est les None dans la liste phi ou psi qui posent problème. J'ai donc triché. Muffufu tu verras :3

**Comment by nanls** [comment]
ha, mais oui, mais ya des none des qu'il y a une nouvelle chaine.

**Comment by nanls** [comment]
C'est donc pour ca que ca marchait que quand il y avait qu'une chaine. rhalala, la prise de tete. XD
