### ISSUE TITLE
mise en place des tables (full sqlalchemy) 

### ISSUE THREAD

**Issue by nanls** [Athenais/M2BI-db-project#9]
- [ ] configuration de la bdd sur l'app [Ath]
- [ ] tables : @NicolasBourassin : pour te montrer je te fait la table pdb vu qu'elle se suffit à elle même, mais ensuite dit moi quelles tables tu veux faire ? 
  - [x] pdb 
  - [x] chain
  - [ ] angle 
   - [x] annotations

**Comment by nanls** [comment]
==== /!\ A moins que j'ai mal noté : ====

pour stocker les angles phi et psi : 
> In sequence order, phi (φ) is the C(i-1),N(i),Ca(i),C(i) torsion angle and psi (ψ) is the N(i),Ca(i),C(i),N(i+1) torsion angle.

on avait fini par faire une seule table. avec les PK étant (id_pdb, num_Ca)

or, je sais pas si c'est la fatigue ou quoi, mais je crois qu'il y aura chevauchement des primary keys, là... non ? oO

**Comment by nanls** [comment]
Tain, mais mème pour la simple table PDB, j'ai des questions, haha. 

J'ai mis : 

- `id_pdb`  : un varchar de 4 characteres   
:question:  en majuscule ? en minuscule ?  tel qu'il est fourni ? (mauvaise idée si on veut éviter les doublons)
- `seq` : du texte 
 :question:  en majuscule ? en minuscule ? tel qu'il est fourni ? 
- `resolution` : un float 
:question: mais si c'est pas un cristal, on met `none` ? et si c'est un cristal dont on connaît pas la résolution (au cas ou le pdb serait foireux, mouhaha)? 
- `header` : 
:question: le header tel quel ? genre juste du texte ? (je me souviens plus pourquoi on avait besoin de ca...) :/ 

Je me sens un peu couillon à me prendre la tête sans réussir à trancher, alors je vous en fait pas ici, des fois que vous auriez des pistes, haha. :smile:

**Comment by NicolasBourassin** [comment]
Est-ce que tu as regardé le document "schéma entité-relation" sur le drive (pas sûr qu'on puisse le stocker ici) ? J'ai reporté ce qu'il y avait sur le schéma papier en ajoutant liens et cardinalités, essaie de checker si ça te semble cohérent et sensé. 
En attendant je checke tes questions, je te dis dès que j'ai une réponse à ce sujet

**Comment by NicolasBourassin** [comment]
Pour la confection des tables je vais commencer par Chaine vu que Annotation et Angle en dépendent ;)

**Comment by NicolasBourassin** [comment]
"pour stocker les angles phi et psi :" j'avais noté que les clés étrangères étaient "id_**chaine**, num_Ca". id_chaine permet d'éviter les chevauchements je pense, SAUF les chevauchements lorsqu'on s'intéresse au même Ca de la même chaîne du même pdb, mais pas au même angle (phi ou psi).

Du coup ça devrait se régler avec une nouvelle PK composée des FK "id_chaine, num_Ca" et de la PK "type (= phi ou psi)"

Hésite pas à me dire si ça te semble pas logique, je me pose aussi plein de questions, on n'aurait pas dû tarder autant à recopier le schéma au propre vu que nos notes sont un peu floues x)

**Comment by CharlottePerin** [comment]
Effectivement, je pense qu'il y aura un chevauchement pour les PK de phi psi, la solution de nicolas parait bien
Pour éviter les problèmes de majuscules, minuscules etc, on pourrait faire un toupper ou tolower avant de stocker dans la base (la magie du python)

**Comment by NicolasBourassin** [comment]
Bonne idée le toupper/tolower !

**Comment by nanls** [comment]
Angle : 
id_pdb 
num_atom
val_phi
val_psi

**Comment by nanls** [comment]
done
